accounts/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

books/urls.py
from django.urls import path

from .views import BookListView,  BookCreateView, BookUpdateView, BookDeleteView, book_details_view

app_name = 'book'

urlpatterns = [
    path('', BookListView.as_view(), name='list_view'),
    path('<int:pk>/', book_details_view, name='details_view'),
    path('new/', BookCreateView.as_view(), name='create_view'),
    path('<int:pk>/update/', BookUpdateView.as_view(), name='update_view'),
    path('<int:pk>/delete/', BookDeleteView.as_view(), name='delete_view'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('books/', include('books.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext, gettext_lazy as _


class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null=True, blank=True, verbose_name=_('age'))

books/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.utils.translation import gettext, gettext_lazy as _


class Book(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name=_('user'))
    title = models.CharField(max_length=200, verbose_name=_('title'))
    author = models.CharField(max_length=200, verbose_name=_('author'))
    translator = models.CharField(max_length=200, blank=True, verbose_name=_('translator'))
    content = models.TextField(verbose_name=_('content'))
    price = models.PositiveBigIntegerField(verbose_name=_('price'))
    cover = models.ImageField(upload_to='covers/', blank=True, verbose_name=_('cover'))
    datetime_created = models.DateTimeField(default=timezone.now, verbose_name=_('datetime_created'))
    datetime_modified = models.DateTimeField(auto_now=True, verbose_name=_('datetime_modified'))

    class Meta:
        verbose_name = _('book')
        verbose_name_plural = _('books')
        ordering = ['-datetime_created']

    def __str__(self):
        return f'{self.author}: {self.title}'

    def get_absolute_url(self):
        return reverse('book:details_view', args=[self.id])


class Comment(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name=_('user'))
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='comments', verbose_name=_('book'))
    text = models.TextField(verbose_name=_('text'))
    is_active = models.BooleanField(default=True, verbose_name=_('is_active'))
    recommend = models.BooleanField(default=True, verbose_name=_('recommend'))
    datetime_created = models.DateTimeField(auto_now_add=True, verbose_name=_('datetime_created'))

    class Meta:
        verbose_name = _('comment')
        verbose_name_plural = _('comments')
        ordering = ['-datetime_created']

    def __str__(self):
        return f'{self.user}: {self.text}'

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        # fields = UserCreationForm.Meta.fields + ('age',)
        fields = ('username', 'age', 'email', )


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        # fields = UserCreationForm.Meta.fields + ('age',)
        fields = ('username', 'age', 'email', )

books/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', 'recommend', )

accounts/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy

from .forms import CustomUserCreationForm


class SignUpView(generic.CreateView):
    form_class = CustomUserCreationForm
    template_name = 'registration/signup.html'
    success_url = reverse_lazy('login')

books/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from .models import Book
from .forms import CommentForm


class BookListView(ListView):
    model = Book
    paginate_by = 4
    template_name = 'books/list_view.html'
    context_object_name = 'books'


# class BookDetailsView(DetailView):
#     model = Book
#     template_name = 'books/details_view.html'
def book_details_view(request, pk):
    book = get_object_or_404(Book, pk=pk)
    # get book comments
    book_comments = book.comments.all()

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.book = book
            new_comment.user = request.user
            new_comment.save()
    else:
        comment_form = CommentForm()
    context = {'book': book, 'comments': book_comments, 'comment_form': comment_form}
    return render(request, 'books/details_view.html', context)


class BookCreateView(LoginRequiredMixin, CreateView):
    model = Book
    fields = ['user', 'title', 'author', 'translator', 'content', 'price', 'cover']
    template_name = 'books/create_view.html'


class BookUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Book
    fields = ['title', 'author', 'translator', 'content', 'price', 'cover']
    template_name = 'books/update_view.html'

    def test_func(self):
        obj = self.get_object()
        return obj.user == self.request.user


class BookDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Book
    template_name = 'books/delete_view.html'
    success_url = reverse_lazy('book:list_view')

    def test_func(self):
        obj = self.get_object()
        return obj.user == self.request.user

pages/views.py
from django.views.generic import ListView

from books.models import Book


class HomePageView(ListView):
    model = Book
    paginate_by = 4
    template_name = 'books/list_view.html'
    context_object_name = 'books'

books/templates/books/create_view.html
{% extends '_base.html' %}
{% load crispy_forms_filters %}

{% block title %}
	اضافه کردن کتاب
{% endblock %}

{% block content %}
    <div class="container mt-4" dir="rtl">
    <div class="row">
        <div class="col-9">
            <div class="card shadow my-3">
                <h5 class="card-header bg-success text-light px-5">فرم</h5>
                <div class="px-5 pt-3 pb-5">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group py-2">
                            {{ form.user|as_crispy_field }}
                        </div>
                        <div class="form-group py-2">
                            <label class="py-1">عنوان کتاب:</label>
                            <input type="text" class="form-control" placeholder="" name="title">
                        </div>
                        <div class="form-group py-2">
                            <label class="py-1">نویسنده:</label>
                            <input type="text" class="form-control" placeholder="" name="author">
                        </div>
                        <div class="form-group py-2">
                            <label class="py-1">مترجم:</label>
                            <input type="text" class="form-control" placeholder="" name="author">
                        </div>
                        <div class="form-group py-2">
                            <label class="py-1">قیمت:</label>
                            <input type="text" class="form-control" placeholder="" name="price">
                        </div>
                        <div class="form-group py-2">
                            <label class="py-1">توضیحات کتاب:</label>
                            <textarea class="form-control" name="content" rows="8" placeholder=""></textarea>
                        </div>
                        <div>
                            {{ form.cover|as_crispy_field }}
                        </div>
                        <button type="submit" class="btn btn-success mt-2">ذخیره</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-3">

                <div class="card my-3 shadow">
                    <h5 class="card-header bg-warning text-light">راهنما</h5>
                    <div class="card-body">
                        <p class="card-text">
                            اطلاعات کتاب را در فرم این صفحه وارد کنید و سپس بر روی دکمه ذخیره کلیک کنید.
                        </p>
                    </div>
                </div>

        </div>
    </div>
</div>
{% endblock %}

books/templates/books/delete_view.html
{% extends '_base.html' %}
{% load crispy_forms_filters %}

{% block title %}
	حذف کردن کتاب
{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <h1>  حذف کتاب {{ book.title }} </h1>
        <p>آِیا مطمئنین ؟</p>
        <input class="btn btn-warning mt-3" type="submit" value="بله">
    </form>
{% endblock %}

books/templates/books/details_view.html
{% extends '_base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load persian_translate_numbers %}
{% load humanize %}

{% block title %}
    صفحه جزئیات
{% endblock %}

{% block content %}
    <div class="container mt-5" dir="rtl">
        <div class="">
            <div class="">
                <div class="d-flex justify-content-center">
                    <div class="row w-sm-75 w-100">
                        <div class="col-xs-12 col-md-3 d-flex justify-content-center">
                            <div>
                                {% if book.cover %}
                                    <img src="{{ book.cover.url }}"
                                         class=" shadow img-fluid rounded-start" alt="...">
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-xs-12 col-md-6 text-center text-md-end mt-md-1 mt-4">
                            <h1>{{ book.title }}</h1>
                            <h5 class="small my-1"><span class="text-muted">نویسنده: </span>{{ book.author }}</h5>
                            <h5 class="small my-1"><span class="text-muted">مترجم: </span>{{ book.translator }}</h5>
                            <h5 class="small my-1"><span class="text-muted">ایجاد کننده: </span>{{ book.user }}</h5>
                            {% if user.is_authenticated %}
                                {% if book.user == user %}
                                    <a class="btn btn-warning" href="{% url 'book:update_view' book.id %}"> ویرایش</a>
                                    <span> | </span>
                                    <a class="btn btn-danger" href="{% url 'book:delete_view' book.id %}"> حذف</a>
                                {% endif %}
                            {% endif %}
                        </div>
                        <div class="col-xs-12 col-md-3 d-flex flex-column">
                            <h3 class="align-self-center pt-2 text-muted align-self-md-end">
                                {{ book.price|translate_numbers|intcomma:False }}
                            </h3>
                        </div>
                    </div>
                </div>

                <div class="d-flex justify-content-center">
                    <div class="my-3 p-5 w-sm-75 w-100">
                        {{ book.content|linebreaks }}
                    </div>
                </div>

                {% if comments %}
                    <div class="d-flex justify-content-center">
                        <div class="card shadow my-3 p-5 w-sm-75 w-100">
                            <h2 class="mb-5">نظرات:</h2>
                            {% for comment in comments %}
                                {% if comment.is_active %}
                                    <div class="border-bottom mb-3">
                                        <h5 class="mb-3">{{ comment.user.username }}</h5>
                                        {% if comment.recommend %}
                                            <p class="text text-success">این کتاب را توصیه می کنم .</p>
                                        {% else %}
                                            <p class="text text-danger">این کتاب را توصیه نمی کنم .</p>
                                        {% endif %}
                                        <p>{{ comment.text|linebreaks }}</p>
                                    </div>
                                {% endif %}

                            {% endfor %}

                        </div>
                    </div>
                {% endif %}

                {% if user.is_authenticated %}
                    <div class="d-flex justify-content-center">
                        <div class="card shadow my-3 p-5 w-sm-75 w-100">
                            <h3>نظر خود را وارد کنید:</h3>
                            <form method="POST">
                                {% csrf_token %}
                                {#                        <div class="form-group py-2">#}
                                {#                            <label class="py-1" for="author_name">نام شما:</label>#}
                                {#                            <input type="text" class="form-control" placeholder="علی علوی" name="author_name">#}
                                {#                        </div>#}
                                {#                        <div class="form-group py-2">#}
                                {#                            <label class="py-1" for="email">ایمیل شما:</label>#}
                                {#                            <input type="email" class="form-control" placeholder="example@gmail.com" name="email">#}
                                {#                        </div>#}
                                <div class="form-group py-2">
                                    <label class="py-1" for="comment_text">متن نظر:</label>
                                    <textarea class="form-control" name="text" rows="3"
                                              placeholder="نظر خود را اینجا وارد کنید."></textarea>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="recommend">
                                    <label class="form-check-label">
                                        پیشنهاد می کنم
                                    </label>
                                </div>
                                <button type="submit" class="btn btn-primary mt-3">ارسال</button>
                            </form>
                        </div>
                    </div>
                {% else %}
                    <div>

                        <div class="card my-3 shadow">
                            <h5 class="card-header bg-danger text-light">راهنما</h5>
                            <div class="card-body">
                                <p class="card-text">
                                    برای ثبت نظر <a style="text-decoration: none" href="{% url 'login' %}">ورود</a> کنید
                                </p>
                            </div>
                        </div>

                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

books/templates/books/list_view.html
{% extends '_base.html' %}

{% block title %}
    لیست کتاب ها
{% endblock %}

{% block content %}
    <div class="container mt-4">
        <div class="row flex-row-reverse justify-content-md-center">
            {% for book in books %}
                <div class="card m-2" style="max-width: 45%">
                    <div class="row g-0 h-100" dir="rtl">
                        <div class="col-md-4">
                            {% if book.cover %}
                                <img src="{{ book.cover.url }}"
                                     class="img-fluid rounded-start" alt="...">
                            {% endif %}
                        </div>
                        <div class="col-md-8 h-100">
                            <div class="d-flex flex-column justify-content-between h-100">
                                <div class="card-body">
                                    <a style="text-decoration: none; color: black" href="{{ book.get_absolute_url }}">
                                        <h3 class="card-title">کتاب {{ book.title }}</h3></a>
                                    <p class="card-text pt-3">{{ book.content|truncatewords:30 }}</p>
                                    <p class="text-muted">نویسنده: {{ book.author }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center mt-3">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">قبلی </a></li>
            {% endif %}
            <li class="page-item"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">بعدی</a></li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

books/templates/books/update_view.html
{% extends '_base.html' %}
{% load crispy_forms_filters %}

{% block title %}
	ویرایش کردن کتاب
{% endblock %}

{% block content %}
    <div class="container mt-4" dir="rtl">
    <div class="row">
        <div class="col-9">
            <div class="card shadow my-3">
                <h5 class="card-header bg-success text-light px-5">فرم</h5>
                <div class="px-5 pt-3 pb-5">
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                    {{ form|crispy }}
{#                        <div class="form-group py-2">#}
{#                            <label class="py-1">عنوان کتاب:</label>#}
{#                            <input type="text" class="form-control" placeholder="" name="title">#}
{#                        </div>#}
{#                        <div class="form-group py-2">#}
{#                            <label class="py-1">توضیحات کتاب:</label>#}
{#                            <textarea class="form-control" name="text" rows="8" placeholder=""></textarea>#}
{#                        </div>#}
                        <input class="btn btn-success mt-2" type="submit" value="ذخیره">
                    </form>
                </div>
            </div>
        </div>
        <div class="col-3">

                <div class="card my-3 shadow">
                    <h5 class="card-header bg-warning text-light">راهنما</h5>
                    <div class="card-body">
                        <p class="card-text">
                            اطلاعات کتاب را در فرم این صفحه وارد کنید و سپس بر روی دکمه ذخیره کلیک کنید.
                        </p>
                    </div>
                </div>

        </div>
    </div>
</div>
{% endblock %}

templates/_base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>{% block title %}

    {% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-info" dir="rtl">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static 'icons/book.png' %}" alt="" height="30"
                 class="d-inline-block align-text-top">
        </a>
        <a class="navbar-brand mx-3" href="{% url 'home' %}">کتاب یار</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">خانه</a>
                {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'book:create_view' %}">اضافه کردن کتاب</a>
                {% endif %}

            </div>
        </div>
        {% if user.is_authenticated %}
            <div class="mx-2 text-white">خوش آمدی {{ user.username }} | <a class="link-light text-decoration-none"
                                                                           href="{% url 'logout' %}">خروج</a></div>
        {% else %}
            <div class="mx-2 text-white"><a class="link-light text-decoration-none" href="{% url 'login' %}">ورود</a> |
                <a class="link-light text-decoration-none" href="{% url 'signup' %}">ثبت نام</a></div>
        {% endif %}
    </div>
</nav>

<div class="container">
    {% block content %}

    {% endblock %}
</div>

<footer class="bg-light text-center text-lg-start mt-5">
    <div class="text-center bg-grey">
        <p>وبسایت کتاب <a class="text-dark" href="https://pouriashirali.iran.liara.run/" target="_blank">پوریا شیرالی
            پور</a></p>
    </div>
</footer>

<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

</body>
</html>